server:
  host: 192.168.228.128
spring:
  datasource:
    url: jdbc:mysql://${server.host}:3306/wenhu?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: ${server.host}
    port: 6379
    database: 0
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${server.host}:8848
        group: wenhu
      config:
        server-addr: ${server.host}:8848 # 作为配置中心，必须优先加载
        group: wenhu
        file-extension: yaml
        prefix: wenhu-config
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
